import backToTop from "../js/modules/backToTop.js";
import AosModule from "../js/modules/AosModule.js";
import PopupModule from "../js/modules/PopupModule.js";
import ScrollModule from "../js/modules/ScrollModule.js";
import SliptModule from "../js/modules/SliptModule.js";
import ScrollParallax from "../js/modules/ScrollParallax.js";
import Hover from "../js/modules/Hover.js";
import ToggleMenu from "../js/modules/ToggleMenu.js";
import ToggleSearch from "../js/modules/ToggleSearch.js";
import CheckedField from "../js/modules/CheckedField.js";
import Select2Module from "../js/modules/Select2Module.js";
import TabsModule from "../js/modules/TabsModule.js";
import SwiperModule from "../js/modules/SwiperModule.js";
import LoadingModule from "../js/modules/LoadingModule.js";
import HeaderDropdown from "../js/modules/HeaderDropdown.js";
import CursorModule from "../js/modules/CursorModule.js";
import CustomSelect from "../js/modules/CustomSelect.js";
import FancyBoxModule from "../js/modules/FancyBoxModule.js";
import SelectQtyModule from "../js/modules/SelectQtyModule.js";
import UploadImage from "../js/modules/UploadImage.js";
import EditField from "../js/modules/EditField.js";
import TogglePassword from "../js/modules/TogglePassword.js";
import FullPageModule from "../js/modules/FullPageModule.js";
import gallery from "../js/modules/GalleryModule.js";
import playVideo from "../js/modules/playVideo.js";

window.addEventListener("DOMContentLoaded", () => {
  gallery();
  LoadingModule();
  ScrollModule();
  SliptModule();
  backToTop();
  AosModule();
  PopupModule();
  ScrollParallax();
  Hover();
  ToggleMenu();
  ToggleSearch();
  CheckedField();
  Select2Module();
  TabsModule();
  SwiperModule();
  HeaderDropdown();
  CursorModule();
  CustomSelect();
  FancyBoxModule();
  SelectQtyModule();
  UploadImage();
  EditField();
  TogglePassword();
  FullPageModule();
  playVideo();
});
