import AosModule from "./module/AosModule.js";
import SwiperModule from "./module/SwiperModule.js";
import Select2Module from "./module/Select2Module.js";
import GalleryModule from "./module/GalleryModule.js";
import TabModule from "./module/TabModule.js";
import HeaderModule from "./module/HeaderModule.js";
import faq from "./module/faq.js";
import seeMore from "./module/seeMore.js";
import selectPhone from "./module/selectPhone.js";
import uploadCV from "./module/uploadCV.js";
import popup from "./module/popup.js";
import scrollAni from "./module/scrollAni.js";
import Pagi from "./module/pagi.js";
import CountUpModule from "./module/CountUpModule.js";
import filterSp from "./module/filterSp.js";
import LinksMain from "./module/linksMain.js";
import Ip from "./module/ip.js";
import danhMuc from "./module/danhMuc.js";
import Quantity from "./module/quantity.js";
import Cmt from "./module/cmt.js";
import HomeJs from "./module/Home.js";

window.addEventListener("DOMContentLoaded", () => {
    Pagi();
    AosModule();
    TabModule();
    SwiperModule();
    GalleryModule();
    HeaderModule();
    faq();
    seeMore();
    selectPhone(); 
    uploadCV();
    popup();
    scrollAni();
    CountUpModule();
    Select2Module();
    filterSp();
    LinksMain();
    Ip();
    danhMuc();
    Quantity();
    Cmt();
    HomeJs();
});